package com.hxngxd.enums;

public enum Permission {

    MANAGE_REVIEWS,
    DELETE_OWN_ACCOUNT,
    DELETE_LOWER_ACCOUNT,
    CHANGE_OTHERS_ROLE,
    CHANGE_OTHERS_ACCOUNT_STATUS,
    CHANGE_OTHER_PASSWORD_EMAIL,
    EDIT_OTHERS_PROFILE,
    MANAGE_BOOKS,
    SEND_NOTIFICATIONS,
    MANAGE_SYSTEM

}